# Generated by Django 5.1.5 on 2025-02-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='context',
            new_name='content',
        ),
    ]
